#!/bin/bash

cd /home/ec2-user

# Install python3
yum -y install python3-3.7.9-1.amzn2.0.2

# Install pip
yum -y install python3-pip-9.0.3
pip3 install -Iv --upgrade pip==20.2.1

# Install awscli and python dev libraries
pip install --user -r scripts/requirements.txt
